AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (v2.1) Telegram chat summarization bot with DynamoDB memory and Explicit API.

# ===================================================================
# 파라미터 정의
# ===================================================================
Parameters:
  TelegramTokenParameter:
    Type: String
    NoEcho: true # 텔레그램 토큰이 노출되지 않도록 설정
  GeminiApiKeyParameter:
    Type: String
    NoEcho: true # Gemini API 키가 노출되지 않도록 설정

# ===================================================================
# AWS 자원 정의
# ===================================================================
Resources:

  # API Gateway 명시적 정의
  SummarizerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod # 'Prod' 스테이지
      Auth:
        DefaultAuthorizer: NONE
      # CORS 설정 (테스트에 유용함)
      Cors:
        AllowMethods: "'POST,OPTIONS'"  
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # 람다 함수
  SummarizerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler # 핵심 핸들러
      Runtime: python3.10
      Timeout: 30 # 30초 타임아웃 설정
      MemorySize: 512 # 512MB 메모리 할당
      Architectures:
        - x86_64
      Environment:
        Variables:
          # 직접 cli에서 입력하는 것으로 유출 방지
          TELEGRAM_TOKEN: !Ref TelegramTokenParameter
          GEMINI_API_KEY: !Ref GeminiApiKeyParameter
          DYNAMO_TABLE_NAME: !Ref ChatLogsTable 
      
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /bot
            Method: post
            # "암시적" API ->"명시적" API로 변경
            RestApiId: !Ref SummarizerApi

      # 함수 DynamoDB 테이블 접근 권한 부여.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatLogsTable 

  # DynamoDB 테이블
  ChatLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "chat_id"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "chat_id"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true

# ===================================================================
# 출력
# ===================================================================
Outputs:
  SummarizerFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SummarizerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bot"